import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { ReactLenis} from 'lenis/react'
import { store } from '../Store' 
import { ReduxProvider } from "./Provider/ReduxProvider";

const lato = Lato({
  weight: ['400', '700' , '900'],
  subsets: ["latin"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.svg',
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.svg" sizes="any" />
      </head>
      <body
        className={`${lato.variable} font-sans antialiased`}
      >
         <ReactLenis root />
         <ReduxProvider >
         {children}
         </ReduxProvider>
    
      </body>
    </html>
  );
}
